### ISSUE TITLE
Problem with `Enum` when running

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/gui-executor#6]
I am making a module to be included in the contingency UI, to copy the camera information from CSL to the TH (when a new camera comes in):

```
from enum import Enum
from gui_executor.exec import exec_ui

UI_MODULE_DISPLAY_NAME = "Camera"


class CSL_SITE_ID(str, Enum):

    CSL = "CSL"
    CSL1 = "CSL1"
    CSL2 = "CSL2"


@exec_ui()
def load_cam_info(csl_site: CSL_SITE_ID = CSL_SITE_ID.CSL, setup_id: int = 98):

    print("Loading cam info")
```

(the exact content of the function is left out, as it is not relevant for the reported problem)

I get a very nice combobox in the contingency UI, but when I press the run button, I get this error in the Console where I started the UI:

```
Traceback (most recent call last):
  File "/Users/sara/work/Instrumentation/Plato/softwareDevelopment/gui-executor/src/gui_executor/view.py", line 352, in run
    tmp.write(create_code_snippet(self._func, self._args, self._kwargs, call_func=False))
  File "/Users/sara/work/Instrumentation/Plato/softwareDevelopment/gui-executor/src/gui_executor/utils.py", line 222, in create_code_snippet
    response = {func.__name__}({stringify_args(args)}{', ' if args else ''}{stringify_kwargs(kwargs)})
  File "/Users/sara/work/Instrumentation/Plato/softwareDevelopment/gui-executor/src/gui_executor/utils.py", line 199, in stringify_kwargs
    return ", ".join([f"{k}={custom_repr(v)}" for k, v in kwargs.items()])
  File "/Users/sara/work/Instrumentation/Plato/softwareDevelopment/gui-executor/src/gui_executor/utils.py", line 199, in <listcomp>
    return ", ".join([f"{k}={custom_repr(v)}" for k, v in kwargs.items()])
  File "/Users/sara/work/Instrumentation/Plato/softwareDevelopment/gui-executor/src/gui_executor/utils.py", line 191, in custom_repr
    return m[1]
TypeError: 'NoneType' object is not subscriptable
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

**Comment by rhuygen** [comment]
The problem is in the regular expression that matches the `repr()` of the Enum. The fix is very simple:

```
m = re.fullmatch(r"<([\w.]+): (\d+)>", repr(arg))
```
should become 
```
m = re.fullmatch(r"<([\w.]+): (.*)>", repr(arg))
```
